import { Injectable, NotFoundException, UnauthorizedException, BadRequestException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { DeviceStatus, DeviceType } from '../../prisma/generated/client';
import * as crypto from 'crypto';

@Injectable()
export class DeviceService {
  constructor(private readonly prisma: PrismaService) {}

  /**
   * Generate a secure API key
   */
  private generateApiKey(): string {
    return `atlas_${crypto.randomBytes(32).toString('hex')}`;
  }

  /**
   * Hash an API key for storage
   */
  private hashApiKey(apiKey: string): string {
    return crypto.createHash('sha256').update(apiKey).digest('hex');
  }

  /**
   * Register a new device and generate API key
   */
  async registerDevice(data: {
    tenantId: string;
    name: string;
    deviceType: DeviceType;
    location?: string;
    description?: string;
    createdBy: string;
  }) {
    // Check if device with same name already exists for this tenant
    const existingDevice = await this.prisma.device.findFirst({
      where: {
        tenantId: data.tenantId,
        name: data.name,
      },
    });

    if (existingDevice) {
      throw new BadRequestException(
        `A device with the name "${data.name}" already exists for this tenant. Please use a different name or regenerate the API key for the existing device.`,
      );
    }

    // Generate API key
    const apiKey = this.generateApiKey();
    const apiKeyHash = this.hashApiKey(apiKey);

    // Create device
    const device = await this.prisma.device.create({
      data: {
        tenantId: data.tenantId,
        name: data.name,
        deviceType: data.deviceType,
        location: data.location,
        description: data.description,
        apiKey: apiKeyHash,
        apiKeyHash: apiKeyHash,
        status: 'INACTIVE',
        createdBy: data.createdBy,
      },
      include: {
        tenant: {
          select: {
            id: true,
            name: true,
            slug: true,
          },
        },
      },
    });

    // Log the registration
    await this.prisma.deviceLog.create({
      data: {
        tenantId: data.tenantId,
        deviceId: device.id,
        action: 'REGISTERED',
        description: `Device registered by user ${data.createdBy}`,
      },
    });

    // Return device with plain API key (only shown once!)
    return {
      ...device,
      apiKeyPlain: apiKey, // This is the only time we return the plain key
    };
  }

  /**
   * Get all devices for a tenant
   */
  async getDevicesByTenant(tenantId: string) {
    const devices = await this.prisma.device.findMany({
      where: { tenantId },
      include: {
        _count: {
          select: { logs: true },
        },
      },
      orderBy: { createdAt: 'desc' },
    });

    return devices;
  }

  /**
   * Get a single device by ID
   */
  async getDeviceById(deviceId: string, tenantId: string) {
    const device = await this.prisma.device.findFirst({
      where: {
        id: deviceId,
        tenantId,
      },
      include: {
        logs: {
          take: 50,
          orderBy: { createdAt: 'desc' },
        },
        _count: {
          select: { logs: true },
        },
      },
    });

    if (!device) {
      throw new NotFoundException('Device not found');
    }

    return device;
  }

  /**
   * Regenerate API key for a device
   */
  async regenerateApiKey(deviceId: string, tenantId: string, userId: string) {
    const device = await this.prisma.device.findFirst({
      where: { id: deviceId, tenantId },
    });

    if (!device) {
      throw new NotFoundException('Device not found');
    }

    // Generate new API key
    const newApiKey = this.generateApiKey();
    const newApiKeyHash = this.hashApiKey(newApiKey);

    // Update device
    const updatedDevice = await this.prisma.device.update({
      where: { id: deviceId },
      data: {
        apiKey: newApiKeyHash,
        apiKeyHash: newApiKeyHash,
        status: 'INACTIVE', // Deactivate until new key is verified
        updatedAt: new Date(),
      },
    });

    // Log the regeneration
    await this.prisma.deviceLog.create({
      data: {
        tenantId,
        deviceId,
        action: 'API_KEY_REGENERATED',
        description: `API key regenerated by user ${userId}`,
      },
    });

    return {
      ...updatedDevice,
      apiKeyPlain: newApiKey, // Return plain key only once
    };
  }

  /**
   * Update device details
   */
  async updateDevice(
    deviceId: string,
    tenantId: string,
    data: {
      name?: string;
      location?: string;
      description?: string;
      status?: DeviceStatus;
      metadata?: any;
    },
  ) {
    const device = await this.prisma.device.findFirst({
      where: { id: deviceId, tenantId },
    });

    if (!device) {
      throw new NotFoundException('Device not found');
    }

    // If updating name, check for duplicates
    if (data.name && data.name !== device.name) {
      const existingDevice = await this.prisma.device.findFirst({
        where: {
          tenantId,
          name: data.name,
          id: { not: deviceId }, // Exclude current device
        },
      });

      if (existingDevice) {
        throw new BadRequestException(
          `A device with the name "${data.name}" already exists for this tenant. Please use a different name.`,
        );
      }
    }

    const updatedDevice = await this.prisma.device.update({
      where: { id: deviceId },
      data: {
        ...data,
        updatedAt: new Date(),
      },
    });

    // Log status changes
    if (data.status && data.status !== device.status) {
      await this.prisma.deviceLog.create({
        data: {
          tenantId,
          deviceId,
          action: 'STATUS_CHANGED',
          description: `Status changed from ${device.status} to ${data.status}`,
        },
      });
    }

    return updatedDevice;
  }

  /**
   * Delete a device
   */
  async deleteDevice(deviceId: string, tenantId: string) {
    const device = await this.prisma.device.findFirst({
      where: { id: deviceId, tenantId },
    });

    if (!device) {
      throw new NotFoundException('Device not found');
    }

    await this.prisma.device.delete({
      where: { id: deviceId },
    });

    return { message: 'Device deleted successfully' };
  }

  /**
   * Authenticate device using API key
   */
  async authenticateDevice(apiKey: string) {
    const apiKeyHash = this.hashApiKey(apiKey);

    const device = await this.prisma.device.findUnique({
      where: { apiKey: apiKeyHash },
      include: {
        tenant: {
          select: {
            id: true,
            name: true,
            slug: true,
            status: true,
          },
        },
      },
    });

    if (!device) {
      throw new UnauthorizedException('Invalid API key');
    }

    if (device.status !== 'ACTIVE') {
      throw new UnauthorizedException(`Device is ${device.status.toLowerCase()}`);
    }

    if (device.tenant.status !== 'ACTIVE') {
      throw new UnauthorizedException('Tenant account is not active');
    }

    // Update last seen
    await this.prisma.device.update({
      where: { id: device.id },
      data: { lastSeenAt: new Date() },
    });

    return device;
  }

  /**
   * Log device activity
   */
  async logDeviceActivity(
    deviceId: string,
    action: string,
    description?: string,
    ipAddress?: string,
    metadata?: any,
  ) {
    const device = await this.prisma.device.findUnique({
      where: { id: deviceId },
    });

    if (!device) {
      throw new NotFoundException('Device not found');
    }

    await this.prisma.deviceLog.create({
      data: {
        tenantId: device.tenantId,
        deviceId,
        action,
        description,
        ipAddress,
        metadata,
      },
    });

    // Update device IP if provided
    if (ipAddress && ipAddress !== device.ipAddress) {
      await this.prisma.device.update({
        where: { id: deviceId },
        data: { ipAddress },
      });
    }
  }

  /**
   * Get device logs
   */
  async getDeviceLogs(deviceId: string, tenantId: string, limit: number = 100) {
    const device = await this.prisma.device.findFirst({
      where: { id: deviceId, tenantId },
    });

    if (!device) {
      throw new NotFoundException('Device not found');
    }

    const logs = await this.prisma.deviceLog.findMany({
      where: { deviceId },
      orderBy: { createdAt: 'desc' },
      take: limit,
    });

    return logs;
  }

  /**
   * Get device statistics for a tenant
   */
  async getDeviceStats(tenantId: string) {
    const devices = await this.prisma.device.findMany({
      where: { tenantId },
    });

    const stats = {
      total: devices.length,
      active: devices.filter((d) => d.status === 'ACTIVE').length,
      inactive: devices.filter((d) => d.status === 'INACTIVE').length,
      suspended: devices.filter((d) => d.status === 'SUSPENDED').length,
      offline: devices.filter((d) => d.status === 'OFFLINE').length,
      byType: {} as Record<string, number>,
      recentlyActive: 0,
    };

    // Count by type
    devices.forEach((device) => {
      stats.byType[device.deviceType] = (stats.byType[device.deviceType] || 0) + 1;
    });

    // Count recently active (within last 5 minutes)
    const fiveMinutesAgo = new Date(Date.now() - 5 * 60 * 1000);
    stats.recentlyActive = devices.filter(
      (d) => d.lastSeenAt && d.lastSeenAt > fiveMinutesAgo,
    ).length;

    return stats;
  }
}
